/*
 * Character
 * ~/characters/Character.java
 * Steven LaGoy
 * Created: 28 August 2024 at 1:07 PM
 * Modified: 29 December 2025
 */

package com.stevenlagoy.presidency.characters;


// IMPORTS ----------------------------------------------------------------------------------------

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


import com.stevenlagoy.presidency.core.TimeManager;
import com.stevenlagoy.presidency.data.Repr;
import com.stevenlagoy.jsonic.JSONObject;
import com.stevenlagoy.jsonic.Jsonic;
import com.stevenlagoy.presidency.characters.attributes.CharacterModel;
import com.stevenlagoy.presidency.characters.attributes.names.Name;
import com.stevenlagoy.presidency.characters.attributes.names.NameManager;
import com.stevenlagoy.presidency.demographics.Demographics;
import com.stevenlagoy.presidency.demographics.DemographicsManager;
import com.stevenlagoy.presidency.map.MapManager;
import com.stevenlagoy.presidency.map.Municipality;

////////////////////////////////////////////////////////////////////////////////////////////////////
//                                           CHARACTER                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * The most basic form of Character, from which other types of Characters
 * inherit.
 * <p>
 * Contains fields and methods which all Characters possess, including
 * Demographics, Name, and Birthday.
 */
public class Character implements Repr<Character>, Jsonic<Character> {

    // STATIC VARIABLES ---------------------------------------------------------------------------------------------------------------------------------------

    /** Minimum age of a Character */
    public final static int MIN_AGE = 0;
    /** Maximum age of a Character */
    public final static int MAX_AGE = 120;

    // INSTANCE VARIABLES -------------------------------------------------------------------------------------------------------------------------------------

    /**
     * Demographics object representing this Character's demographic memberships.
     */
    private Demographics demographics;
    /** Name object representing this Character's name. */
    private Name name;
    /** Municipality in which this Character was born. */
    private Municipality birthplaceMunicipality;
    /** Municipality to which this Character is currently nearest. */
    private Municipality currentLocationMunicipality;
    /**
     * Municipality in which this Character currently resides (primary residence).
     */
    private Municipality residenceMunicipality;
    /** Date on which this character was born. @see #getAge() */
    private LocalDate birthday;
    /** CharacterModel object to be rendered for this Character. */
    private CharacterModel appearance;

    private MapManager mm;

    // CONSTRUCTORS -------------------------------------------------------------------------------------------------------------------------------------------

    public Character() {

    }

    /**
     * Creates a Character with all fields generated by the CharacterManager.
     * 
     * @see #Character(Demographics, Name, Municipality, Municipality, Municipality,
     *      Date, CharacterModel)
     */
    public Character(CharacterManager cm, DemographicsManager dm, MapManager mm, NameManager nm) {
        // Have builder constructor generate all fields
        this(cm, dm, mm, nm, null, null, null, null, null, null, null);
    }

    /**
     * Deep-copies the existing fields of another Character object.
     * Optionally adds to CharacterManager's list of Characters.
     * 
     * @param other              Character to copy fields from.
     * @param addToCharacterList Boolean indicating whether to add the created
     *                           object to the CharacterManager's list.
     */
    public Character(Character other) {
        this.demographics = new Demographics(other.demographics);
        this.name = new Name(other.name);
        this.birthplaceMunicipality = other.birthplaceMunicipality;
        this.currentLocationMunicipality = other.currentLocationMunicipality;
        this.residenceMunicipality = other.residenceMunicipality;
        this.birthday = other.birthday;
        this.appearance = new CharacterModel(other.appearance);
    }

    /**
     * Creates a Character parsed from the Repr buildstring.
     * 
     * @param buildstring        Valid Repr-format buildstring.
     * @param addToCharacterList Boolean indicating whether to add the created
     *                           object to the CharacterManager's list.
     */
    public Character(String buildstring) {
        if (buildstring == null || buildstring.isBlank()) {
            throw new IllegalArgumentException("The given buildstring was null, and a " + getClass().getSimpleName()
                    + " object could not be created.");
        }
        fromRepr(buildstring);
    }

    /**
     * Creates a character from the JSON Object structure.
     * 
     * @param json JSONObject representing a character.
     */
    public Character(JSONObject json) {
        if (json == null) {
            throw new IllegalArgumentException("The passed JSONObject was null, and a " + getClass().getSimpleName()
                    + " object could not be created.");
        }
        fromJson(json);
    }

    /**
     * Creates a Character with the passed values. The CharacterManager will
     * generate
     * values for any {@code null} values passed.
     * 
     * @param demographics           Demographics object representing this
     *                               Character's demographic memberships.
     * @param name                   Name object representing this Character's name.
     * @param birthplaceMunicipality Municipality in which this Character was born.
     * @param residenceMunicipality  Municipality in which this Character currently
     *                               resides and is located (primary residence).
     * @param birthday               Date on which this character was born.
     * @param appearance             CharacterModel object to be rendered for this
     *                               Character.
     */
    public Character(
        CharacterManager cm,
        DemographicsManager dm,
        MapManager mm,
        NameManager nm,
        Demographics demographics,
        Name name,
        Municipality birthplaceMunicipality,
        Municipality residenceMunicipality,
        LocalDate birthday,
        CharacterModel appearance
    ) {
        this(cm, dm, mm, nm, demographics, name, birthplaceMunicipality, residenceMunicipality, residenceMunicipality, birthday, appearance);
    }

    // TODO This should be in the CharacterManager, not here

    /**
     * Creates a Character with the passed values. The CharacterManager will
     * generate
     * values for any {@code null} values passed.
     * 
     * @param demographics                Demographics object representing this
     *                                    Character's demographic memberships.
     * @param name                        Name object representing this Character's
     *                                    name.
     * @param birthplaceMunicipality      Municipality in which this Character was
     *                                    born.
     * @param currentLocationMunicipality Municipality to which this Character is
     *                                    currently nearest.
     * @param residenceMunicipality       Municipality in which this Character
     *                                    currently resides (primary residence).
     * @param birthday                    Date on which this character was born.
     * @param appearance                  CharacterModel object to be rendered for
     *                                    this Character.
     */
    public Character(
        CharacterManager cm,
        DemographicsManager dm,
        MapManager mm,
        NameManager nm,
        Demographics demographics,
        Name name,
        Municipality birthplaceMunicipality,
        Municipality currentLocationMunicipality,
        Municipality residenceMunicipality,
        LocalDate birthday,
        CharacterModel appearance
    ) {
        this.demographics = demographics != null ? demographics
                : dm.generateWeightedDemographics();
        this.name = name != null ? name : nm.generateName(this.demographics);
        this.birthplaceMunicipality = birthplaceMunicipality != null ? birthplaceMunicipality
                : mm.selectMunicipality(this.demographics);
        this.residenceMunicipality = residenceMunicipality != null ? residenceMunicipality
                : mm.selectMunicipality(this.demographics);
        this.currentLocationMunicipality = currentLocationMunicipality != null ? currentLocationMunicipality
                : residenceMunicipality != null ? residenceMunicipality
                        : mm.selectMunicipality(this.demographics);
        this.birthday = birthday != null ? birthday : cm.generateBirthday(this.demographics);
        this.appearance = appearance != null ? appearance
                : cm.generateCharacterModel(this.demographics, this.birthday);
    }

    // GETTERS AND SETTERS ------------------------------------------------------------------------------------------------------------------------------------

    // Demographics

    public Demographics getDemographics() {
        return this.demographics;
    }

    public void setDemographics(Demographics demographics) {
        this.demographics = demographics;
    }

    // Name

    public Name getName() {
        return this.name;
    }

    public void setName(Name name) {
        this.name = name;
    }

    // Birthplace : Municipality

    public Municipality getBirthplaceMunicipality() {
        return this.birthplaceMunicipality;
    }

    public void setBirthplaceMunicipality(Municipality birthplace) {
        this.birthplaceMunicipality = birthplace;
    }

    // Current Location : Municipality

    public Municipality getCurrentLocationMunicipality() {
        return this.currentLocationMunicipality;
    }

    public void setCurrentLocationMunicipality(Municipality currentLocation) {
        this.currentLocationMunicipality = currentLocation;
    }

    // Residence : Municipality
    public Municipality getResidenceMunicipality() {
        return this.residenceMunicipality;
    }

    public void setResidenceMunicipality(Municipality residence) {
        this.residenceMunicipality = residence;
    }

    // Birthday : Date
    public LocalDate getBirthday() {
        return this.birthday;
    }

    public void setBirthday(LocalDate birthday) {
        this.birthday = birthday;
    }

    // Age : int

    public int getAge(TimeManager timeManager) {
        return timeManager.yearsAgo(this.birthday); // TODO how to do this without Engine reference?
    }

    // Appearance : CharacterModel
    public CharacterModel getAppearance() {
        return appearance;
    }

    public void setAppearance(CharacterModel appearance) {
        this.appearance = appearance;
    }

    // REPRESENTATION METHODS ---------------------------------------------------------------------------------------------------------------------------------

    @Override
    public Character fromRepr(String repr) {
        return this;
    }

    @Override
    public String toRepr() {
        String repr = String.format(
                "%s:[name:%sbirthplaceMunicipality=%s;currentLocationMunicipality=%s;residenceMunicipality=%s;birthday=%d;appearance=%s];",
                this.getClass().getName().split("\\.")[this.getClass().getName().split("\\.").length - 1],
                this.name.toRepr(),
                this.birthplaceMunicipality.getNameWithState(),
                this.currentLocationMunicipality.getNameWithState(),
                this.residenceMunicipality.getNameWithState(),
                this.birthday.toString(),
                this.appearance.toRepr());
        return repr;
    }

    @Override
    public Character fromJson(JSONObject json) {

        if (json == null)
            return null;
        // Demographics
        Object demographicsObj = json.get("demographics");
        if (demographicsObj instanceof JSONObject demographicsJson)
            this.demographics = new Demographics(demographicsJson);
        // Name
        Object nameObj = json.get("name");
        if (nameObj instanceof JSONObject nameJson)
            this.name = new Name(nameJson);
        // Birthplace
        Object birthplaceObj = json.get("birthplace");
        if (birthplaceObj instanceof JSONObject birthplaceJson)
            this.birthplaceMunicipality = mm.matchMunicipality(birthplaceJson.getAsString());
        // Current Location
        Object currentLocationObj = json.get("current_location");
        if (currentLocationObj instanceof JSONObject currentLocationJson)
            this.currentLocationMunicipality = mm.matchMunicipality(currentLocationJson.getAsString());
        // Residence
        Object residenceObj = json.get("residence");
        if (residenceObj instanceof JSONObject residenceJson)
            this.currentLocationMunicipality = mm.matchMunicipality(residenceJson.getAsString());
        // Birthday
        Object birthdayObj = json.get("birthday");
        if (birthdayObj instanceof JSONObject birthdayJson)
            this.birthday = TimeManager.dateFromString(birthdayJson.getAsString());
        // Appearance
        Object appearanceObj = json.get("appearance");
        if (appearanceObj instanceof JSONObject appearanceJson)
            this.appearance = appearance.fromJson(appearanceJson);

        return this;
    }

    @Override
    public JSONObject toJson() {
        List<JSONObject> fields = new ArrayList<>();
        fields.add(demographics.toJson());
        fields.add(name.toJson());
        fields.add(new JSONObject("birthplace", birthplaceMunicipality.getNameWithCountyAndState()));
        fields.add(new JSONObject("current_location", currentLocationMunicipality.getNameWithCountyAndState()));
        fields.add(new JSONObject("residence", residenceMunicipality.getNameWithCountyAndState()));
        fields.add(new JSONObject("birthday", birthday.toString()));
        fields.add(appearance.toJson());
        return new JSONObject(String.format("%d", hashCode()), fields);
    }

    // OBJECT METHODS -----------------------------------------------------------------------------------------------------------------------------------------

    /**
     * @see #toRepr()
     */
    @Override
    public String toString() {
        return this.toRepr();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null || this.getClass() != obj.getClass())
            return false;
        Character other = (Character) obj;
        return this.toString().equals(other.toString());
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int hash = 7;
        hash = prime * hash + (demographics == null ? 0 : demographics.hashCode());
        hash = prime * hash + (name == null ? 0 : name.hashCode());
        return hash;
    }

    @Override
    public Character clone() {
        return new Character(this);
    }
}